### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by 4dambarr** [LemonPressYork/website#2]
It's probably best to do design a mockup of the landing page before we implement it. This issue is to keep track of how it's going, please link any sketches in the comments. Important features of the landing pages include:

- Latest Print Issue - show off the artwork, link to issue on https://issuu.com/thelemonpress
- Trending Articles
- Latest Articles

**Comment by benslv** [comment]
I'm happy to try and tackle this one if you want. Have been working on a Figma document if you would like me to link it here.

**Comment by 4dambarr** [comment]
> I'm happy to try and tackle this one if you want. Have been working on a Figma document if you would like me to link it here.

That would be great

**Comment by benslv** [comment]
[Homepage design](https://www.figma.com/file/mMCFCRAF73gSUM5E6pYNLB/Homepage)

Here's what I've got so far. I spent the evening yesterday make a bunch of components which can be reused across the design and easily updated whenever we want.

It's a little standard at the moment so we ought to find a way to give it a bit of character, I think.
